CXX = g++
CXXFLAGS = -g3 -Wall -Wextra
LDFLAGS = -g3

BuildHalvesSolution.out: BuildHalvesSolution.o
	${CXX} ${LDFLAGS} -o $@ $^

BuildHalvesSolution.o: BuildHalvesSolution.cpp 

CharArraySolution.out: CharArraySolution.o
	${CXX} ${LDFLAGS} -o $@ $^

CharArraySolution.o: CharArraySolution.cpp 

FastBuildHalvesSolution.out: FastBuildHalvesSolution.o
	${CXX} ${LDFLAGS} -o $@ $^

FastBuildHalvesSolution.o: FastBuildHalvesSolution.cpp 

IntArraySolution.out: IntArraySolution.o
	${CXX} ${LDFLAGS} -o $@ $^

IntArraySolution.o: IntArraySolution.o 

StringSolution.out: StringSolution.o
	${CXX} ${LDFLAGS} -o $@ $^

StringSolution.o: StringSolution.cpp 

VectorSolution.out: VectorSolution.o
	${CXX} ${LDFLAGS} -o $@ $^

VectorSolution.o: VectorSolution.cpp 

